#####################################################
#####################################################
TEXT_EMBEDDING_SIZES:
  mentalbert: 768
  roberta: 768
  minilm: 384
  bert: 768
IMAGE_EMBEDDING_SIZES:
  clip: 768
  dino: 768
####################################################
#####################################################

dataset: reddit
num_folds: 5
fold: 0

# can be image, text, both
modality: text

use_class_weights: True

model: tlstm

# can be relative or delta
timestamp_kind: 'delta'

# can be tim2vec, learned or zero

image_embeddings_type: clip
text_embeddings_type: mentalbert
# emotion_embeddings_type: bert

window_size: 128 

base_lr: 0.001 #0.00001

model_args:
  hidden_size: 256
  embedding_size: 256
